version: '3.9'
services:

    laravel-backend:
        build:
            context: .
            dockerfile: ./docker/dockerFile
        ports:
            - 8088:8000
        volumes:
            - .:/app
        depends_on:
            - database

    database:
        image: mysql:8.0.27
        env_file:
            - ./docker/.env
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - ${MYSQL_LOCAL_HOME}:/var/lib/mysql
        ports:
            - 3309:3306



